-- ===================================================================
-- ESQUEMA COMPLETO DE BASE DE DATOS PARA SUPABASE (POSTGRESQL)
-- SISTEMA DE GESTIÓN DE PROVEÍDOS Y ELEVACIONES - UNHEVAL EPG
-- ===================================================================

-- 1. TABLA CONFIGURACIÓN
CREATE TABLE IF NOT EXISTS public.configuracion (
    clave TEXT PRIMARY KEY,
    valor TEXT
);

-- 2. TABLA DESTINATARIOS FRECUENTES (Para autocompletado)
CREATE TABLE IF NOT EXISTS public.destinatarios_frecuentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    cargo TEXT,
    frecuencia INTEGER DEFAULT 1
);

-- 3. TABLA PROVEÍDOS
CREATE TABLE IF NOT EXISTS public.proveidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero INTEGER NOT NULL UNIQUE,
    codigo_formateado TEXT NOT NULL,
    anio INTEGER NOT NULL DEFAULT 2026,
    sufijo TEXT NOT NULL DEFAULT '-2026-UNHEVAL/EPG-D',
    tipo TEXT NOT NULL DEFAULT 'SIMPLE',
    destinatarios JSONB DEFAULT '[]'::jsonb,
    destinatario_principal TEXT,
    cargo_principal TEXT,
    asunto TEXT NOT NULL,
    referencia TEXT,
    remitente_ref TEXT,
    registro TEXT,
    fecha_recibido TEXT,
    fecha_emision TEXT,
    lugar_emision TEXT DEFAULT 'Cayhuayna',
    disposicion TEXT,
    check_opciones JSONB DEFAULT '[]'::jsonb,
    dni TEXT,
    titulo_art TEXT,
    estado TEXT DEFAULT 'EMITIDO',
    impreso INTEGER DEFAULT 0,
    veces_impreso INTEGER DEFAULT 0,
    fecha_impresion TEXT,
    eliminado INTEGER DEFAULT 0,
    fecha_eliminacion TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. TABLA ELEVACIONES
CREATE TABLE IF NOT EXISTS public.elevaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero INTEGER NOT NULL UNIQUE,
    codigo_formateado TEXT NOT NULL,
    anio INTEGER NOT NULL DEFAULT 2026,
    sufijo TEXT NOT NULL DEFAULT '-2026-UNHEVAL/EPG-D',
    destinatario TEXT NOT NULL,
    asunto TEXT NOT NULL,
    referencia TEXT,
    remitente_ref TEXT,
    registro TEXT,
    fecha_recibido TEXT,
    fecha_emision TEXT,
    lugar_emision TEXT DEFAULT 'Cayhuayna',
    disposicion TEXT,
    check_opciones JSONB DEFAULT '[]'::jsonb,
    doc_ref TEXT,
    estado TEXT DEFAULT 'EMITIDO',
    impreso INTEGER DEFAULT 0,
    veces_impreso INTEGER DEFAULT 0,
    fecha_impresion TEXT,
    eliminado INTEGER DEFAULT 0,
    fecha_eliminacion TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. TABLA PLANTILLAS
CREATE TABLE IF NOT EXISTS public.plantillas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_doc TEXT NOT NULL,
    nombre TEXT NOT NULL,
    icono TEXT DEFAULT '📋',
    asunto TEXT,
    disposicion TEXT,
    destinatarios JSONB DEFAULT '[]'::jsonb,
    destinatario TEXT,
    check_opciones JSONB DEFAULT '[]'::jsonb,
    es_predeterminada INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. HABILITAR PERMISOS COMPLETOS (Desactivar RLS o permitir acceso total)
ALTER TABLE public.configuracion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.destinatarios_frecuentes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proveidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.elevaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plantillas ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso público/anónimo y autenticado para que funcione al 100%
CREATE POLICY "Permitir todo en configuracion" ON public.configuracion FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en destinatarios_frecuentes" ON public.destinatarios_frecuentes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en proveidos" ON public.proveidos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en elevaciones" ON public.elevaciones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en plantillas" ON public.plantillas FOR ALL USING (true) WITH CHECK (true);
